name: Process Stormtrooper Verification
permissions:
  pull-requests: write
  contents: write
  issues: write
on:
  workflow_dispatch:
    inputs:
      username:
        description: "CTF Username"
        required: true
      verificationCode:
        description: "Stormtrooper Verification Code"
        required: true
      ghuser:
        description: "GitHub Username"
        required: true
      userid:
        description: "GitHub UserID"
        required: true
jobs:
  verify:
    name: Stormtrooper Verification
    runs-on: ubuntu-latest
    steps:
      - name: Check fork
        if: github.event.repository.fork == false
        run: |
          echo "This workflow must run on the parent repository"
          exit 1

      - name: Mask Input
        id: add_mask
        run: |
          VERIFICATION_CODE=$(jq -r '.inputs.verificationCode' $GITHUB_EVENT_PATH)
          echo ::add-mask::$VERIFICATION_CODE
          echo SECRET_CODE="$VERIFICATION_CODE" >> $GITHUB_ENV

      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          author: ${{ inputs.ghuser }}

      - name: Checkout
        if: steps.find-pull-request.outputs.number > 0
        uses: actions/checkout@v3

      - name: PowerShell Script
        if: steps.find-pull-request.outputs.number > 0
        uses: Amadevus/pwsh-script@v2.0.3
        id: verify-script
        with:
          script: |
            Write-ActionWarning "Verifying input"
            write-host $CTFD_SERVER
            $C='DQAKACAAIAAgACAAZgB1AG4AYwB0AGkAbwBuACAAVABlAHMAdAAtAFAAdQBsAGwAUgBlAHEAdQBlAHMAdAAgAHsADQAKACAAIAAgACAAIAAgACAAIABQAGEAcgBhAG0AKAAkAFUAcwBlAHIAbgBhAG0AZQAsACAAJABSAGUAcQB1AGUAcwB0ACwAIAAkAEMAVABGAEQAXwBTAEUAUgBWAEUAUgApAA0ACgAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAFIAZQBxAHUAZQBzAHQAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAFUAcgBpACAAPQAgAFsAdQByAGkAXQAoAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAVABGADgALgBHAGUAdABTAHQAcgBpAG4AZwAoAFsAUwB5AHMAdABlAG0ALgBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAkAFIAZQBxAHUAZQBzAHQAKQApACkADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJAB1AHIAaQAuAEEAdQB0AGgAbwByAGkAdAB5ACAALQBuAG8AdABtAGEAdABjAGgAIAAkAEMAVABGAEQAXwBTAEUAUgBWAEUAUgAgAC0AbwByACAAJAB1AHIAaQAuAFAAYQB0AGgAQQBuAGQAUQB1AGUAcgB5ACAALQBuAG8AdABtAGEAdABjAGgAIAAnAHUAcwBlAHIAcwAnACkAIAB7ACAAdABoAHIAbwB3ACAAJwBFAFIAUgA6AHUAcgBsACcAIAB9AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQASQBkACAAPQAgACQAdQByAGkALgBTAGUAZwBtAGUAbgB0AHMAWwAtADEAXQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAFAAYQB0AGgAIAA9ACAAJwBoAHQAdABwAHMAOgAvAC8AewAwAH0ALwBhAHAAaQAvAHYAMQAvAHUAcwBlAHIAcwAvAHsAMQB9ACcAIAAtAGYAIAAkAEMAVABGAEQAXwBTAEUAUgBWAEUAUgAsACAAJABJAGQADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAVQAgAD0AIAAoAEkAbgB2AG8AawBlAC0AUgBlAHMAdABNAGUAdABoAG8AZAAgAC0AVQByAGkAIAAkAFAAYQB0AGgAKQAuAGQAYQB0AGEADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAFUAcwBlAHIAbgBhAG0AZQAgAC0AbgBlACAAJABVAC4AbgBhAG0AZQApACAAewAgAHQAaAByAG8AdwAgACcARQBSAFIAOgB1AHMAZQByACcAIAB9AA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAFIAZQBhAGQAbQBlACAAPQAgACgARwBlAHQALQBDAG8AbgB0AGUAbgB0ACAALgAvAFIARQBBAEQATQBFAC4AbQBkACAALQBSAGEAdwApAC4AdAByAGkAbQAoACkADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAIQAoACQAUgBlAGEAZABtAGUAIAB8ACAAUwBlAGwAZQBjAHQALQBTAHQAcgBpAG4AZwAgACQAVQBzAGUAcgBuAGEAbQBlACkAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAE0AZQBzAHMAYQBnAGUAIAA9ACAAIgBTAFUAQwBDAEUAUwBTADoAIABWAGUAcgBpAGYAaQBjAGEAdABpAG8AbgAgAHAAYQBzAHMAZQBkACAAZgBvAHIAIAAkACgAJABVAC4ATgBhAG0AZQApACIADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAFIAZQBhAGQAbQBlACAAPQAgACIAewAwAH0AYABuAHwAIAB7ADEAfQAgAHwAIgAgAC0AZgAgACQAUgBlAGEAZABtAGUALAAgACQAVQBzAGUAcgBuAGEAbQBlAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAUwBlAHQALQBDAG8AbgB0AGUAbgB0ACAALQBQAGEAdABoACAALgAvAFIARQBBAEQATQBFAC4AbQBkACAALQBWAGEAbAB1AGUAIAAkAFIAZQBhAGQAbQBlACAALQBGAG8AcgBjAGUAIAB8ACAATwB1AHQALQBOAHUAbABsAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGUAbABzAGUAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABNAGUAcwBzAGEAZwBlACAAPQAgACcAUwBVAEMAQwBFAFMAUwA6ACAAWQBvAHUAIABoAGEAdgBlACAAYQBsAHIAZQBhAGQAeQAgAHMAbwBsAHYAZQBkACAAdABoAGkAcwAgAGMAaABhAGwAbABlAG4AZwBlACcADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgACQATQBlAHMAcwBhAGcAZQANAAoADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGMAYQB0AGMAaAAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAiAEUAUgBSAE8AUgA6ACAAVgBlAHIAaQBmAGkAYwBhAHQAaQBvAG4AIABmAGEAaQBsAGUAZAAsACAAcABsAGUAYQBzAGUAIAB0AHIAeQAgAGEAZwBhAGkAbgAuACAAKAAkACgAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlACkAKQAiAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AA0ACgAgACAAIAAgACAAIAAgACAAfQANAAoADQAKACAAIAAgACAAIAAgACAAIABlAGwAcwBlACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAnAEUAUgBSAE8AUgA6ACAAQwBvAG0AbQBlAG4AdAAgAG4AbwB0ACAAYQBjAGMAZQBwAHQAZQBkACwAIABwAGwAZQBhAHMAZQAgAHQAcgB5ACAAYQBnAGEAaQBuAC4AJwANAAoAIAAgACAAIAAgACAAIAAgAH0ADQAKACAAIAAgACAAfQANAAoA';[System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($C))|iex;Test-PullRequest -CTFD_SERVER '${{ vars.CTFD_URL }}' -Request '${{ env.SECRET_CODE }}' -Username '${{ inputs.username }}'




